import type { Item } from '../types'

const MOCK_IMAGES = [
  'https://picsum.photos/seed/desk/400/500',
  'https://picsum.photos/seed/chair/400/400',
  'https://picsum.photos/seed/laptop/400/550',
  'https://picsum.photos/seed/book1/400/350',
  'https://picsum.photos/seed/bike/400/450',
  'https://picsum.photos/seed/couch/400/380',
  'https://picsum.photos/seed/ipad/400/500',
  'https://picsum.photos/seed/lamp/400/600',
  'https://picsum.photos/seed/shoes/400/420',
  'https://picsum.photos/seed/bag123/400/480',
  'https://picsum.photos/seed/headphone/400/400',
  'https://picsum.photos/seed/monitor22/400/350',
]

export const MOCK_ITEMS: Item[] = [
  {
    id: 'mock-1', user_id: 'u1', title: '9成新 Herman Miller 人体工学椅',
    description: '毕业搬家出，买了一年，非常舒服', price: 350,
    category: 'furniture', condition: 'like_new', status: 'active',
    location: 'Champaign', images: [MOCK_IMAGES[0]], view_count: 42,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    profile: { id: 'u1', nickname: '即将毕业的小明', avatar_url: 'https://api.dicebear.com/7.x/fun-emoji/svg?seed=ming', phone: null, email: null, wechat_openid: null, bio: '', location: 'UIUC', created_at: '', updated_at: '' },
  },
  {
    id: 'mock-2', user_id: 'u2', title: 'MacBook Pro 14寸 M3 Pro 顶配',
    description: 'AppleCare到2026年，无磕碰划痕', price: 1800,
    category: 'electronics', condition: 'like_new', status: 'active',
    location: 'Urbana', images: [MOCK_IMAGES[2]], view_count: 128,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    profile: { id: 'u2', nickname: 'CS大四学长', avatar_url: 'https://api.dicebear.com/7.x/fun-emoji/svg?seed=cs', phone: null, email: null, wechat_openid: null, bio: '', location: 'UIUC', created_at: '', updated_at: '' },
  },
  {
    id: 'mock-3', user_id: 'u3', title: '全新 Nike Air Max 270 女款',
    description: '买错尺码了，US 7.5，全新带盒', price: 75,
    category: 'clothing', condition: 'new', status: 'active',
    location: 'Champaign', images: [MOCK_IMAGES[8]], view_count: 35,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    profile: { id: 'u3', nickname: '爱购物的小红', avatar_url: 'https://api.dicebear.com/7.x/fun-emoji/svg?seed=hong', phone: null, email: null, wechat_openid: null, bio: '', location: 'UIUC', created_at: '', updated_at: '' },
  },
  {
    id: 'mock-4', user_id: 'u1', title: '宜家 KALLAX 书架 4x2格',
    description: '白色，用了一学期，自提', price: 40,
    category: 'furniture', condition: 'good', status: 'active',
    location: 'Urbana', images: [MOCK_IMAGES[1]], view_count: 18,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    profile: { id: 'u1', nickname: '即将毕业的小明', avatar_url: 'https://api.dicebear.com/7.x/fun-emoji/svg?seed=ming', phone: null, email: null, wechat_openid: null, bio: '', location: 'UIUC', created_at: '', updated_at: '' },
  },
  {
    id: 'mock-5', user_id: 'u4', title: 'iPad Pro 12.9 + Apple Pencil 2',
    description: '上课记笔记用的，带壳带膜，可小刀', price: 650,
    category: 'electronics', condition: 'good', status: 'active',
    location: 'Champaign', images: [MOCK_IMAGES[6]], view_count: 88,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    profile: { id: 'u4', nickname: '工院研究生', avatar_url: 'https://api.dicebear.com/7.x/fun-emoji/svg?seed=grad', phone: null, email: null, wechat_openid: null, bio: '', location: 'UIUC', created_at: '', updated_at: '' },
  },
  {
    id: 'mock-6', user_id: 'u5', title: '自行车 Trek FX2 通勤车',
    description: '骑了两年，刚换了新胎和刹车皮', price: 180,
    category: 'vehicles', condition: 'good', status: 'active',
    location: 'Urbana', images: [MOCK_IMAGES[4]], view_count: 56,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    profile: { id: 'u5', nickname: '环保出行', avatar_url: 'https://api.dicebear.com/7.x/fun-emoji/svg?seed=bike', phone: null, email: null, wechat_openid: null, bio: '', location: 'UIUC', created_at: '', updated_at: '' },
  },
  {
    id: 'mock-7', user_id: 'u3', title: 'Bose QC45 降噪耳机',
    description: '图书馆神器，送耳机包', price: 120,
    category: 'electronics', condition: 'good', status: 'active',
    location: 'Champaign', images: [MOCK_IMAGES[10]], view_count: 73,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    profile: { id: 'u3', nickname: '爱购物的小红', avatar_url: 'https://api.dicebear.com/7.x/fun-emoji/svg?seed=hong', phone: null, email: null, wechat_openid: null, bio: '', location: 'UIUC', created_at: '', updated_at: '' },
  },
  {
    id: 'mock-8', user_id: 'u6', title: '合租 Green St 1B1B 暑假转租',
    description: '6-8月，步行UIUC 5分钟，$650/月含水电', price: 650,
    category: 'housing', condition: 'good', status: 'active',
    location: 'Champaign', images: [MOCK_IMAGES[5]], view_count: 210,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    profile: { id: 'u6', nickname: '暑期回国', avatar_url: 'https://api.dicebear.com/7.x/fun-emoji/svg?seed=house', phone: null, email: null, wechat_openid: null, bio: '', location: 'UIUC', created_at: '', updated_at: '' },
  },
  {
    id: 'mock-9', user_id: 'u2', title: '教科书一堆 CS/Math 专业',
    description: 'CS374 CS421 MATH415 等，打包$50带走', price: 50,
    category: 'books', condition: 'fair', status: 'active',
    location: 'Urbana', images: [MOCK_IMAGES[3]], view_count: 22,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    profile: { id: 'u2', nickname: 'CS大四学长', avatar_url: 'https://api.dicebear.com/7.x/fun-emoji/svg?seed=cs', phone: null, email: null, wechat_openid: null, bio: '', location: 'UIUC', created_at: '', updated_at: '' },
  },
  {
    id: 'mock-10', user_id: 'u4', title: '台灯 + USB Hub 组合',
    description: '书桌好伴侣，LED护眼灯+7口Hub', price: 25,
    category: 'daily', condition: 'good', status: 'active',
    location: 'Champaign', images: [MOCK_IMAGES[7]], view_count: 15,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    profile: { id: 'u4', nickname: '工院研究生', avatar_url: 'https://api.dicebear.com/7.x/fun-emoji/svg?seed=grad', phone: null, email: null, wechat_openid: null, bio: '', location: 'UIUC', created_at: '', updated_at: '' },
  },
]
