/*
 * What is left of the mirror test.
 *
 * api/translate.js used to screen the model's output for contact channels,
 * mirroring the contact_info branches of public.content_moderation_check, and
 * the verdicts it asserted were generated by running the real PostgreSQL
 * functions over a corpus rather than written by hand.
 *
 * Both halves of that are gone. 20260903060000 removed the contact_info
 * verdict — sharing contact details is allowed everywhere a member types —
 * and the screen went with it, because a client rule the server does not have
 * is the shape of PR #290: the composer refusing what the insert accepts.
 *
 * The one assertion worth keeping is the tripwire. content_moderation_check's
 * behaviour is pinned by corpora in scripts/moderation-contact-and-ad-policy.
 * test.mjs — 45 ad-evasion variants and 21 ordinary secondhand sentences, run
 * against the real function in a throwaway cluster. Those corpora were
 * generated against one definition of the function. If a later migration
 * redefines it, they have to be regenerated rather than assumed, and this
 * fails to say so.
 */
import test from 'node:test'
import assert from 'node:assert/strict'
import { readdir, readFile } from 'node:fs/promises'

const root = new URL('../', import.meta.url)

test('the corpora were generated against the latest definition of the function', async () => {
  const entries = await readdir(new URL('supabase/migrations/', root))
  const definitions = []
  for (const name of entries.filter(entry => entry.endsWith('.sql')).sort()) {
    const sql = await readFile(new URL(`supabase/migrations/${name}`, root), 'utf8')
    if (sql.includes('FUNCTION public.content_moderation_check')) definitions.push(name)
  }

  // Control: the scan must find the real history, not zero files.
  assert.ok(definitions.length >= 3, `only ${definitions.length} definitions found — the scan missed supabase/migrations/`)

  assert.equal(
    definitions.at(-1),
    '20260904060000_ad_signals_stop_catching_ordinary_listings.sql',
    'content_moderation_check was redefined after 20260904060000 — regenerate the corpora in '
      + 'scripts/moderation-contact-and-ad-policy.test.mjs against the new definition before '
      + 'changing this assertion',
  )
})
