import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const source = relative => readFile(new URL(relative, import.meta.url), 'utf8')

test('retirement PRECHECK fails closed on data, identity, ACL, and ledger drift', async () => {
  const precheck = await source(
    '../supabase/_ops/PRECHECK_20260718_retire_wechat_password_credentials.sql',
  )
  assert.match(precheck, /SET TRANSACTION READ ONLY/)
  assert.match(precheck, /SET LOCAL lock_timeout = '2s'/)
  assert.match(precheck, /SET LOCAL statement_timeout = '30s'/)
  assert.match(precheck, /current_user <> 'postgres'/)
  assert.match(precheck, /NOT relation\.relforcerowsecurity/)
  assert.match(precheck, /unexpected table\/column grantee/)
  assert.match(precheck, /legacy WeChat password RPC ACL drifted/)
  assert.match(precheck, /migration_record_count <> 0/)
  assert.match(precheck, /legacy_rows <> 0/)
  assert.doesNotMatch(precheck, /SELECT\s+password\b/i)
})

test('retirement VERIFY proves exact least privilege and one ledger identity', async () => {
  const verify = await source(
    '../supabase/_ops/VERIFY_20260718_retire_wechat_password_credentials.sql',
  )
  assert.match(verify, /SET TRANSACTION READ ONLY/)
  assert.match(verify, /SET LOCAL lock_timeout = '2s'/)
  assert.match(verify, /'MAINTAIN'/)
  assert.ok(
    verify.indexOf("relation.relkind = 'r'")
      < verify.indexOf('SELECT 1 FROM public.wechat_password_map LIMIT 1'),
    'verify must establish the exact table identity before reading rows',
  )
  assert.match(verify, /function\.proowner = pg_catalog\.to_regrole\('postgres'\)::oid/)
  assert.match(verify, /function\.proconfig = ARRAY\['search_path=pg_catalog'\]::text\[\]/)
  assert.match(verify, /unexpected table\/column grantee remains/)
  assert.match(verify, /unexpected exact-delete RPC grantee/)
  assert.match(verify, /relation_acl\.is_grantable/)
  assert.match(verify, /function_acl\.is_grantable/)
  assert.match(verify, /migration_record_count <> 1 OR migration_collision_count <> 1/)
  assert.match(verify, /version = \$1 AND name = \$2/)
  assert.match(verify, /Supabase migration ledger shape drifted/)
  assert.match(verify, /attribute\.attname = 'version'[\s\S]*'text'::pg_catalog\.regtype/)
  assert.match(verify, /attribute\.attname = 'statements'[\s\S]*'text\[\]'::pg_catalog\.regtype/)
  assert.match(verify, /retire_wechat_password_credentials/)
  assert.match(verify, /guarded migration statement receipt/)
  assert.match(verify, /cardinality\(migration_statements\) <> 19/)
  assert.match(verify, /IN SHARE ROW EXCLUSIVE MODE/)
  assert.match(verify, /FULL OUTER JOIN supabase_migrations\.schema_migrations/)
  assert.match(verify, /production_ledger_identity_cardinality_mismatch/)
  assert.match(verify, /actual_count <> 108/)
  assert.match(verify, /unique_version_count <> 108/)
  assert.match(verify, /unique_identity_count <> 108/)
  assert.match(verify, /migration_statements\[1\][\s\S]*migration_statements\[19\]/)
  assert.match(verify, /migration ledger contains a null\/empty statement/)
  assert.match(verify, /array_ndims\(migration_statements\)/)
  assert.match(verify, /array_lower\(migration_statements, 1\)[\s\S]*<> 1/)
  assert.match(verify, /array_upper\(migration_statements, 1\)[\s\S]*<> 19/)
  assert.match(verify, /COALESCE\(pg_catalog\.strpos\(migration_statements\[1\]/)
  assert.doesNotMatch(verify, /pg_catalog\.coalesce/i)
  assert.match(verify, /ledger_actual_count <> 109/)
  assert.match(verify, /guard_identity_count <> 108/)
  assert.match(verify, /regexp_matches\([\s\S]*migration_statements\[5\]/)
  assert.match(verify, /FULL OUTER JOIN live_predecessors/)
  assert.match(verify, /guarded receipt identity projection drifted/)
  assert.match(verify, /ec5c0180e406d6ee92bebfaf85e8b2f3/)
  assert.match(verify, /guarded receipt pinned identity checksum drifted/)
  assert.match(verify, /COALESCE\([\s\S]*obj_description\(map_table, 'pg_class'\)/)
  assert.doesNotMatch(verify, /SELECT\s+password\b/i)
})

test('retirement behavioral regression is bounded, isolated, and rollback-only', async () => {
  const regression = await source(
    '../supabase/_ops/REGRESSION_20260718_retire_wechat_password_credentials.sql',
  )
  assert.match(regression, /NEVER run against production/)
  assert.match(regression, /SET LOCAL lock_timeout = '5s'/)
  assert.match(regression, /SET LOCAL statement_timeout = '2min'/)
  assert.match(regression, /current_user <> 'postgres'/)
  assert.doesNotMatch(regression, /^COMMIT;$/m)
  assert.match(regression.trimEnd(), /ROLLBACK;$/)
})

test('runbook requires the bounded ledger executor and rejects unverifiable paths', async () => {
  const runbook = await source('../RUNBOOK.md')
  assert.match(runbook, /wechat-retirement-migration-executor\.mjs/)
  assert.match(runbook, /lock_timeout=5s/)
  assert.match(runbook, /statement_timeout=2min/)
  assert.match(runbook, /conflicting ledger\/table lock[\s\S]*within five seconds/)
  assert.match(runbook, /wechat-retirement-postgres-rehearsal\.mjs/)
  assert.match(runbook, /LOCAL_DISPOSABLE_POSTGRES_ONLY/)
  assert.match(runbook, /hosted[\s\S]*`apply_migration` call/)
  assert.match(runbook, /short-lived named Supabase secret/)
  assert.match(runbook, /SUPABASE_DB_SSLROOTCERT/)
  assert.match(runbook, /sslmode=verify-full/)
  assert.match(runbook, /108 exact live[\s\S]*execution-deny guards/)
  assert.match(runbook, /109-file/)
  assert.match(runbook, /SHARE ROW EXCLUSIVE/)
  assert.match(runbook, /FULL OUTER JOIN/)
  assert.match(runbook, /extracted 108-row identity set/)
  assert.match(runbook, /normalized[\s\S]*body/)
  assert.match(runbook, /guarded execution/)
  assert.match(runbook, /empty legacy map is not proof/)
  assert.match(runbook, /mapless pairs/)
  assert.match(runbook, /deleting `WECHAT_USER_PASSWORD_SALT`[\s\S]*does not invalidate/)
  assert.match(runbook, /--expected-inventory-sha256/)
  assert.match(runbook, /two[\s\S]*identical complete user sets/)
  assert.match(runbook, /Standard Protection[\s\S]*password-era/)
  assert.match(runbook, /every reachable retained URL or[\s\S]*generated, branch, author,[\s\S]*custom\/Production/)
  assert.match(runbook, /no cookie or bypass token/)
  assert.match(runbook, /generated URL[\s\S]*retention/)
  assert.match(runbook, /never promote or roll back[\s\S]*7fb25c3957b14004c861200f3499267ad5163699/)
  assert.match(runbook, /Prefer: count=exact[\s\S]*Content-Range/)
  assert.match(runbook, /94[\s\S]*historical \+ 38 candidate[\s\S]*132/)
  assert.match(runbook, /freeze account creation\/deletion/)
  assert.match(runbook, /point-in-time restore[\s\S]*reintroduce/)
  assert.match(runbook, /restore point predates[\s\S]*mapless HMAC-era credential/)
  assert.match(runbook, /after all[\s\S]*password rotations/)
})

test('WeChat setup warns that mapless HMAC credentials survive salt removal', async () => {
  const guide = await source('../docs/WECHAT_MP_SETUP.md')
  assert.match(guide, /HMAC-era users with no map row/)
  assert.match(guide, /removing `WECHAT_USER_PASSWORD_SALT`[\s\S]*does not invalidate/)
  assert.match(guide, /mapless\/map-backed orphan stops all mutation/)
  assert.match(guide, /--expected-inventory-sha256/)
  assert.match(guide, /validates `x-total-count`/)
  assert.match(guide, /Standard Protection[\s\S]*every reachable retained URL or alias:[\s\S]*generated, branch,[\s\S]*author,[\s\S]*custom\/Production/)
  assert.match(guide, /no login[\s\S]*cookie or automation-bypass token/)
  assert.match(guide, /exact[\s\S]*`Content-Range`/)
  assert.match(guide, /restore from before rotation[\s\S]*resurrect/)
})

test('disposable rehearsal gives every database child a bounded environment', async () => {
  const rehearsal = await source('./wechat-retirement-postgres-rehearsal.mjs')
  assert.match(rehearsal, /env = boundedRehearsalEnvironment\(\)/)
  assert.match(rehearsal, /spawn\(PSQL,[\s\S]*env: boundedRehearsalEnvironment\(baseDirectory\)/)
  assert.match(rehearsal, /env: boundedRehearsalEnvironment\(workdir\)/)
})
